# FILE: cf-backend/wrangler.toml
name = "private-ai-agent"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "ai-agent-db"
database_id = "12f93cbc-53fc-44c8-9d7c-b480a3a4e80c"

[[vectorize]]
binding = "VECTORIZE_MEMORY"
index_name = "ai-agent-memory"

[[vectorize]]
binding = "VECTORIZE_KNOWLEDGE"
index_name = "ai-agent-knowledge"

[[kv_namespaces]]
binding = "CACHE"
id = "0e6b40443e1d42b4b7384df435cc7cf5"

[vars]
SEARXNG_URL = "https://kantan.cat"
E2B_API_KEY = ""
ENVIRONMENT = "production"

[triggers]
crons = ["0 * * * *"]
